### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by jlaksana** [bbmcmann/307MovieProject#64]
Update the readme to include the steps for developers to setup their development environment and what steps they should take to make contributions.
Also update the project description on github.
EXTRA: create a icon logo that appears on the chrome tab
Add sequence diagram: https://drive.google.com/file/d/15jEi9DxDtci87fFSzrfHVOTYW8_m95v5/view?usp=sharing
Add class diagram: https://drive.google.com/file/d/1P3RCt0tJhiephHuyNuNjHkO5_wGm8W78/view?usp=sharing

**Comment by jlaksana** [comment]
1 hour

**Comment by bbmcmann** [comment]
30 min for demo
