### ISSUE TITLE
Research movie API and how it works

### ISSUE THREAD

**Issue by bbmcmann** [bbmcmann/307MovieProject#8]
We need a public and free API to query movies and related information. This will provide the basic information about a movie for many of the pages on our site without needing to store the data in our own database. 
Give a report of the API, link to documentation, and key features.

**Comment by jlaksana** [comment]
**Report:**
name: themoviedb.org
link: https://developers.themoviedb.org/3/getting-started/introduction 
Features:
- Search by title (https://developers.themoviedb.org/3/search/search-movies)
- get movie details by id (https://developers.themoviedb.org/3/movies/get-movie-details)
- get the current popular movies (https://developers.themoviedb.org/3/movies/get-popular-movies)
- get recommendations for a given movie id (https://developers.themoviedb.org/3/movies/get-movie-recommendations)
- a ton more listed on documentation

notes:
I created an account. Contact me directly for login info and the API key. To my knowledge, it is completely free.

**Comment by jlaksana** [comment]
~1hr
